"""Declarative metadata for every application-backed tool."""

from __future__ import annotations

from pydantic import BaseModel

from webchat.orchestration.tools.inputs import (
    BookingLookupForm,
    BusinessInformationQuery,
    DealershipMessageDraftInput,
    DealershipQuery,
    DealershipScopeQuery,
    EmptyInput,
    Filters,
    OpeningHoursQuery,
    PageVehicleSelection,
    PartExchangeEstimate,
    PartExchangeEstimateForm,
    ServiceQuery,
    StableId,
    VehicleComparison,
    VehicleModelComparison,
    VehiclePreferenceRequest,
    VehicleSearch,
    WorkflowDraftInput,
    WorkshopAmendmentInput,
    WorkshopAmendmentSlotContext,
)

from .contracts import Invocation, ResultMode, Risk, ToolDefinition


def _tool(
    name: str,
    title: str,
    description: str,
    input_model: type[BaseModel],
    *renderers: str,
    risk: Risk = "read",
    mode: ResultMode = "render",
    invocation: Invocation = "planner",
    preconditions: tuple[str, ...] = (),
    retrieval_examples: tuple[str, ...] = (),
    trusted_input_model: type[BaseModel] | None = None,
) -> ToolDefinition:
    return ToolDefinition(
        id=name,
        title=title,
        description=description,
        input_model=input_model,
        trusted_input_model=trusted_input_model,
        executor_reference=name,
        risk=risk,
        invocation=invocation,
        allowed_renderers=frozenset(renderers),
        result_mode=mode,
        preconditions=preconditions,
        retrieval_examples=retrieval_examples,
    )


CORE_TOOLS: tuple[ToolDefinition, ...] = (
    _tool(
        "search_vehicles",
        "Search vehicle stock",
        "Start a new search across current vehicle inventory when the customer supplies constraints or explicitly asks to browse stock. Constraints include make, model, budget, mileage, fuel, transmission, body style, availability, dealership town, sort order, and explicit exclusions via excludedMakes, excludedModels, excludedFuelTypes, excludedTransmissions, or excludedBodyStyles. For open-ended help choosing a car with no constraints, use show_vehicle_preferences. For changes to displayed matching results, use refine_vehicle_search.",
        VehicleSearch,
        "vehicle_list",
        "suggestion_list",
        retrieval_examples=(
            "Find vehicles matching these make, model, price, mileage, fuel, gearbox, body-style, availability, location, year, or ranking constraints.",
            "Start a fresh constrained vehicle search that does not inherit an earlier search.",
        ),
    ),
    _tool(
        "reset_vehicle_search",
        "Show all available vehicles",
        "Clear the complete current vehicle search and show all available stock. Use when the customer explicitly asks to reset, start over, remove every filter, show all cars, or show all available vehicles. Do not use refine_vehicle_search because refinements preserve omitted filters.",
        EmptyInput,
        "vehicle_list",
        "suggestion_list",
        retrieval_examples=(
            "Show me all available cars and clear the filters.",
            "Reset my vehicle search and start over.",
        ),
    ),
    _tool(
        "refine_vehicle_search",
        "Refine the current vehicle search",
        "Modify, re-sort, exclude categories from, or paginate the current server-owned vehicle search while preserving every unspecified filter. Translate explicit negative preferences into excludedMakes, excludedModels, excludedFuelTypes, excludedTransmissions, or excludedBodyStyles. Use only for a follow-up to displayed matching results; use search_vehicles for a new search.",
        VehicleSearch,
        "vehicle_list",
        "suggestion_list",
        preconditions=("current_vehicle_search",),
        retrieval_examples=(
            "Show more of the current matching vehicles.",
            "Sort the matching vehicles by cheapest price, lowest mileage, or newest first.",
            "Keep the current search constraints but exclude a make, model, fuel, transmission, or body style.",
        ),
    ),
    _tool(
        "select_page_vehicles",
        "Filter visible page vehicles",
        "Filter or rank only the vehicles currently rendered on the website page. vehicleIds must come from trusted page context.",
        PageVehicleSelection,
        "vehicle_list",
        "suggestion_list",
        preconditions=("trusted_page_vehicle_ids",),
    ),
    _tool(
        "get_vehicle_facets",
        "Read vehicle search choices",
        "Read current makes, models, body styles, fuels, transmissions, budgets, and mileage choices from live stock.",
        EmptyInput,
        mode="evidence",
    ),
    _tool(
        "show_vehicle_preferences",
        "Show vehicle preference choices",
        "Show application-owned vehicle-search choice chips. Use startingPoint when the customer asks for help finding or choosing a car but has not supplied any search constraint. For a named dimension, set reuseCurrentSearch=true only when the customer explicitly wants to refine displayed results; otherwise the chooser starts fresh.",
        VehiclePreferenceRequest,
        "suggestion_list",
        retrieval_examples=(
            "Help me find or choose another car, but I do not have any preferences yet.",
        ),
    ),
    _tool(
        "get_vehicle",
        "Get vehicle details",
        "Get current details for one trusted vehicle ID.",
        StableId,
        "vehicle_details",
        preconditions=("trusted_vehicle_id",),
    ),
    _tool(
        "get_vehicle_availability",
        "Check vehicle availability",
        "Check live availability for one trusted vehicle ID.",
        StableId,
        "vehicle_availability",
        preconditions=("trusted_vehicle_id",),
    ),
    _tool(
        "compare_vehicles",
        "Compare trusted vehicles",
        "Compare two or three trusted vehicle IDs shown in the current context.",
        VehicleComparison,
        "vehicle_comparison",
        "suggestion_list",
        preconditions=("trusted_vehicle_ids",),
    ),
    _tool(
        "compare_vehicle_models",
        "Compare named vehicle models",
        "Resolve and compare two or three customer-supplied vehicle model descriptions against live available stock.",
        VehicleModelComparison,
        "vehicle_comparison",
        "suggestion_list",
    ),
    _tool(
        "list_offers",
        "Browse published offers",
        "List current published vehicle finance offers, optionally filtered by make or PCP/PCH product type. Do not use for questions asking what a finance term means.",
        Filters,
        "offer_list",
    ),
    _tool(
        "get_offer",
        "Get offer details",
        "Get one current published offer using a trusted offer ID.",
        StableId,
        "offer_list",
        preconditions=("trusted_offer_id",),
    ),
    _tool(
        "list_dealerships",
        "Find dealerships",
        "Find Northstar dealership locations and contact details. With a customer-supplied town, return that resolved location; without a town, preserve plural/all-location scope. Supports spelling variation through the application resolver.",
        DealershipQuery,
        "dealership_list",
        "suggestion_list",
    ),
    _tool(
        "show_dealership_contact_options",
        "Show dealership contact options",
        "Show application-owned ways to contact a Northstar dealership: request a callback, send a message, view contact details, or view opening hours. Use when the customer accepts an earlier offer to help them contact a dealership but has not chosen a contact method.",
        EmptyInput,
        "suggestion_list",
        retrieval_examples=(
            "The customer says yes to the assistant's offer to help contact a dealership.",
            "Show dealership contact choices without guessing whether the customer wants a callback, message, details, or opening hours.",
        ),
    ),
    _tool(
        "list_dealership_departments",
        "List departments at all dealerships",
        "List which sales, service, and parts departments are available across all Northstar dealerships. Use for plural, all-location, or each-dealership requests; never collapse this operation to one location.",
        EmptyInput,
        "dealership_list",
        retrieval_examples=(
            "What departments do the dealerships have?",
            "What departments do all the dealerships have?",
            "List departments at each Northstar location.",
        ),
    ),
    _tool(
        "find_dealership_departments",
        "Find departments at one dealership",
        "Find sales, service, and parts departments for one customer-supplied town or the sole dealership in current context. If several dealerships are displayed and none is named, location clarification is required.",
        DealershipScopeQuery,
        "dealership_list",
        "suggestion_list",
        preconditions=(
            "single_dealership_or_location",
            "trusted_optional_dealership_id",
        ),
        retrieval_examples=(
            "What departments does this dealership have?",
            "Which departments are at the Stockport dealership?",
        ),
    ),
    _tool(
        "get_dealership",
        "Get dealership details",
        "Get contact and location details for the sole dealership in current trusted context. Never select one ID from several displayed dealerships; use list_dealerships with a customer-supplied town or clarify.",
        StableId,
        "dealership_list",
        preconditions=("trusted_dealership_id", "sole_displayed_dealership"),
    ),
    _tool(
        "get_opening_hours",
        "Get dealership opening hours",
        "Get all opening hours for the sole dealership in current trusted context. Never select one ID from several displayed dealerships; use list_opening_hours with a customer-supplied town or clarify.",
        StableId,
        "opening_hours",
        preconditions=("trusted_dealership_id", "sole_displayed_dealership"),
    ),
    _tool(
        "list_opening_hours",
        "Find opening hours",
        "Find regular weekly opening hours across all dealerships or filter by a customer-supplied town, weekday, and department. Do not use for bank-holiday or other holiday-exception questions; use list_holiday_opening_hours. With exactly one dealership in current context, preserve that location. With several displayed dealerships, an unfiltered list request means the full displayed/all-location scope; never choose one arbitrary ID. Use calendar context to translate relative days such as tomorrow.",
        OpeningHoursQuery,
        "opening_hours",
        "suggestion_list",
        preconditions=(
            "single_dealership_or_all",
            "trusted_optional_dealership_id",
        ),
        retrieval_examples=(
            "Show opening hours for all dealerships.",
            "What are the opening hours at this location?",
        ),
    ),
    _tool(
        "list_holiday_opening_hours",
        "Find holiday opening hours",
        "Show published bank-holiday and other holiday opening-hour exceptions without mixing in regular weekday hours. Return all dealerships unless the customer supplies a town or exactly one dealership is established by trusted context.",
        DealershipScopeQuery,
        "opening_hours",
        "suggestion_list",
        preconditions=(
            "single_dealership_or_all",
            "trusted_optional_dealership_id",
        ),
        retrieval_examples=(
            "Are you open on the bank holiday?",
            "Show the published holiday opening hours.",
            "What are the Christmas or public-holiday hours?",
        ),
    ),
    _tool(
        "get_business_information",
        "Answer confirmed business policy",
        "Look up authoritative Northstar finance, privacy, part-exchange, or general business information for the customer's exact question. Use for policy questions; an unavailable result means the policy is not confirmed.",
        BusinessInformationQuery,
        "business_information",
    ),
    _tool(
        "get_service_information",
        "Check whether a named workshop service is offered",
        "Check whether Northstar supports one customer-named workshop service, then report its live price or cost, duration, and description. Use for questions such as tyre fitting cost, interim-service price, or whether car cleaning is supported.",
        ServiceQuery,
        "service_list",
        "suggestion_list",
        retrieval_examples=(
            "Do you offer this named workshop service?",
            "What does this workshop service cost and how long does it take?",
        ),
    ),
    _tool(
        "list_service_types",
        "Browse workshop services",
        "List every currently supported Northstar workshop service. Do not use when the customer named a specific service; use get_service_information instead.",
        EmptyInput,
        "service_list",
        retrieval_examples=(
            "What workshop service types do you support?",
            "Show the complete workshop service catalogue.",
        ),
    ),
    _tool(
        "list_workshop_locations",
        "Find workshop locations",
        "List dealership locations that provide workshop services.",
        EmptyInput,
        "workshop_location_list",
    ),
    _tool(
        "list_test_drive_slots",
        "Find test-drive times",
        "Find current test-drive slots for one trusted, currently available vehicle.",
        Filters,
        "test_drive_slot_picker",
        "vehicle_availability",
        preconditions=("trusted_vehicle_id",),
    ),
    _tool(
        "list_workshop_slots",
        "Find workshop appointment times",
        "Find current workshop appointment slots for a named or selected service, with optional dealership town and dates. If no service is supplied, returns a service chooser.",
        Filters,
        "slot_list",
        "service_list",
        "suggestion_list",
        retrieval_examples=(
            "I want to book a new workshop appointment.",
            "Find workshop times for a service, optionally at a location or date.",
        ),
    ),
    _tool(
        "refine_workshop_slots",
        "Refine the current workshop-slot search",
        "Change the service, location, or date of the current workshop appointment search while preserving every unspecified constraint. A newly supplied service replaces the previous service. Use only for a follow-up to a current workshop search.",
        Filters,
        "slot_list",
        "service_list",
        "suggestion_list",
        preconditions=("current_workshop_search",),
        retrieval_examples=(
            "Find a different location or date for that workshop service.",
            "Is there workshop availability in this town for it?",
            "Change my current workshop booking search from interim service to tyre fitting.",
        ),
    ),
    _tool(
        "request_workshop_booking_lookup_form",
        "Request booking verification",
        "Show the secure four-field lookup form to find, amend, or cancel an existing workshop booking.",
        BookingLookupForm,
        "private_booking_lookup",
    ),
    _tool(
        "request_part_exchange_estimate_form",
        "Request estimate details",
        "Show the application-owned form for an indicative part-exchange estimate, prefilling any known registration, mileage, or condition.",
        PartExchangeEstimateForm,
        "part_exchange_estimate_form",
    ),
    _tool(
        "estimate_part_exchange",
        "Calculate indicative part exchange",
        "Calculate the platform's indicative part-exchange range after registration, mileage, and condition are known.",
        PartExchangeEstimate,
        "part_exchange_estimate",
    ),
    _tool(
        "request_offer_enquiry_form",
        "Open offer sales-enquiry form",
        "Open the application-owned inline sales-enquiry form for an authoritative selected offer without persisting a draft. This internal browser capability is never planner-callable and never submits the enquiry.",
        WorkflowDraftInput,
        "draft",
        mode="workflow",
        invocation="internal",
    ),
    _tool(
        "prepare_sales_enquiry",
        "Prepare sales enquiry",
        "Open or prefill an application-owned sales enquiry draft. Prefill enquiry type and message only from relevant customer-authored conversation content or trusted selected-vehicle context; a generic request to make an enquiry is not message content. Missing fields are collected by the form; this does not submit anything.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("contextual_dealership_prefill",),
    ),
    _tool(
        "prepare_test_drive",
        "Prepare test-drive booking",
        "Prepare a test-drive booking draft after a customer selects a live slot. Missing contact fields are collected by the form; this does not confirm a booking.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
    ),
    _tool(
        "prepare_vehicle_interest",
        "Prepare vehicle interest",
        "Prepare a vehicle-interest draft for a trusted reserved vehicle. Missing contact fields are collected by the form; this does not register interest.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("trusted_vehicle_id",),
    ),
    _tool(
        "prepare_callback",
        "Prepare callback request",
        "Open or prefill a callback-request draft. Prefill reason, department, and preferred time only from relevant customer-authored conversation content; a generic callback request is not a reason. Missing fields are collected by the application form; this does not submit the request.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("contextual_dealership_prefill",),
    ),
    _tool(
        "prepare_workshop_booking",
        "Prepare workshop booking",
        "Prepare a workshop booking draft after a live slot is selected. Prefill optional notes only when the customer supplied relevant notes; never copy the booking request into notes. This never confirms the booking.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
    ),
    _tool(
        "prepare_workshop_amendment",
        "Prepare booking amendment",
        "Prepare changes to a previously verified workshop booking. This never applies the change without application confirmation.",
        WorkshopAmendmentInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("verified_booking",),
        trusted_input_model=WorkshopAmendmentSlotContext,
    ),
    _tool(
        "prepare_workshop_cancellation",
        "Prepare booking cancellation",
        "Prepare cancellation of a previously verified workshop booking. This never cancels without application confirmation.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("verified_booking",),
    ),
    _tool(
        "prepare_dealership_message",
        "Prepare dealership message",
        "Open or prefill a message form for a dealership department. Prefill subject and message only when the customer supplied actual content to deliver in the current conversation; a request to send or leave a message expresses workflow intent and is not itself message content. Missing fields are collected by the form, and trusted dealership context may preselect its location. This does not send anything.",
        DealershipMessageDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("contextual_dealership_prefill",),
    ),
    _tool(
        "prepare_part_exchange",
        "Prepare part-exchange follow-up",
        "Prepare a part-exchange follow-up draft. Missing details are collected by the form; this does not submit anything.",
        WorkflowDraftInput,
        "draft",
        "confirmation",
        risk="draft",
        mode="workflow",
        preconditions=("contextual_dealership_prefill",),
    ),
)
